
export let books: any = [
    { id:1,name: 'Half Girlfriend', image:'https://m.media-amazon.com/images/I/712HEn9SNwL.jpg', genre: 'Romance',price: 200 ,description:'Half Girlfriend is an Indian English coming of age, young adult romance novel by Indian author Chetan Bhagat. The novel, set in rural Bihar, New Delhi, Patna, and New York, is the story of a Bihari boy in quest of winning over the girl he loves.',author:'Chetan Bhagat',fav:false,cart:false},
    { id:2,name: 'You can Win', image: 'https://5.imimg.com/data5/SELLER/Default/2020/10/ZB/JR/SC/113288716/11-06-2020-jpg-500x500.jpg', genre: 'Self-help Book', price: 130,description:'You Can Win Summary motivates people and take things right from your daily life and turns them into positive thrust. This book is for those who pursue balanced personality and who want to move towards success with positivity. This is easy to read a self-help book.',author:'Shiv Khera',fav:false,cart:false},
    { id:3,name: 'Girl in Room No 105', image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTl1mw11kjbUoEkH91CLEexqu0p_9iSczgoe2RIPNi0GtRlZDHBG2p4nduusGnD6ZqURek&usqp=CAU', genre: 'Thriller', price: 150,description:'It tells about an IIT coaching class tutor who goes to wish his ex-girlfriend on her birthday and finds her murdered. The rest of the story is his journey where he stands by his ex-girlfriend after her death to find justice. The book also addresses the stereotypes and political issues in India.',author:'Chetan Bhagat',fav:false,cart:false},
    { id:4,name: 'Treasure Island', image: 'https://m.media-amazon.com/images/I/819gepUWtdS.jpg', genre: 'Adventure', price: 270,description:'The story is about a young boy named Jim Hawkins who goes on a dangerous adventure to recover buried treasure. Along the way, he encounters mutinous pirates, marooned castaways, frightening tales of ghosts, and much more.' ,author:'Robert Louis Stevenson',fav:false,cart:false},
    { id:5,name: 'The Three Musketers', image:'https://m.media-amazon.com/images/I/51ewNXKhOzL._SX342_SY445_QL70_ML2_.jpg',genre:'Adventure',price:250,description:'The Three Musketeers, novel by Alexandre Dumas père, published in French as Les Trois Mousquetaires in 1844. SUMMARY: A historical romance, it relates the adventures of four fictional swashbuckling heroes who lived under the French kings Louis XIII and Louis XIV, who reigned during the 17th and early 18th centuries.',author:'Alexandre Dumas',fav:false,cart:false},
    { id:6,name: 'Happy go Lucky', image: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1642710101i/58989873._UY400_SS400_.jpg', genre: 'Comedy', price: 1200,description:'In Happy-Go-Lucky, his new collection of autobiographical sketches, he broods about the cosmic injustice of Covid-19: noting that a million Americans died in the pandemic, he fumes that he didnt get to choose a single one of them. Though Sedaris may want his words to hurt, even kill, they often rebound.' ,author:'David Sedaris',fav:false,cart:false},
    { id:7,name: 'Ghost Stories', image: 'https://m.media-amazon.com/images/I/41ED6zmx7fL.jpg', genre: 'Horror', price: 300 ,description:'A ghost story is any piece of fiction, or drama, that includes a ghost, or simply takes as a premise the possibility of ghosts or characters belief in them. The "ghost" may appear of its own accord or be summoned by magic.',author:'Stephen King',fav:false,cart:false},
    {id:8,name:'It Ends with us',image:'https://m.media-amazon.com/images/I/81s0B6NYXML.jpg',genre:'Romance',price:399,description:'It Ends with Us is a book that follows a girl named Lily who has just moved and is ready to start her life after college. Lily then meets a guy named Ryle and she falls for him. As she is developing feelings for Ryle, Atlas, her first love, reappears and challenges the relationship between Lily and Ryle.',author:'Collen Hoover',fav:false,cart:false},
]